spring:
  application:
    name: eureka
server:
  port: 8761
eureka:
  client:
#    启动报错是因为两个
#    获取注册信息 因为本身是注册中心所以不需要获取注册信息
    fetch-registry: false
#    注册到注册中心去 因为本身是注册中心所以不需要注册
    register-with-eureka: false